In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print("1-dim",arr1,sep='\n',end='\n\n')

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2-dim",arr2,sep='\n',end='\n\n')

arr3 = np.array([[[1, 2], [3, 4]],[[5,6], [6,7]]])
print("multi-dim",arr3,sep='\n')

1-dim
[1 2 3 4 5]

2-dim
[[1 2 3]
 [4 5 6]]

multi-dim
[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


In [ ]:
zeros = np.zeros((4,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones = np.ones((4,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
identity = np.eye(6)
print(identity)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
full_array = np.full((2, 3), 100)
print(full_array)

[[100 100 100]
 [100 100 100]]


In [ ]:
range_arr = np.arange(1,30,2)
print(range_arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


In [ ]:
range_arr = np.arange(0,28,2)
print(range_arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26]


In [ ]:
lin_space = np.linspace(5, 50, 6)
print(lin_space)

[ 5. 14. 23. 32. 41. 50.]


In [ ]:
#np.random.seed(10)
rand_arr = np.random.randint(6)
print(rand_arr)

1


In [ ]:
rand_int = np.random.randint(25,45)
print(rand_int)

44


In [ ]:
rand_float = np.random.rand(3,4)
print(rand_float)

[[0.8568503  0.35165264 0.75464769 0.29596171]
 [0.88393648 0.32551164 0.1650159  0.39252924]
 [0.09346037 0.82110566 0.15115202 0.38411445]]


In [ ]:
rand_int = np.random.randint(1, 6, (5,6))
print(rand_int)

[[1 3 2 1 2 2]
 [1 2 3 5 3 2]
 [2 5 1 1 2 1]
 [5 5 1 3 4 4]
 [4 3 3 4 1 4]]


In [ ]:
rand_choice = np.random.choice(['html','c','css','java','flaslk'], 5)
print(rand_choice)

['flaslk' 'java' 'c' 'c' 'c']


In [ ]:
shape = np.shape([[1, 2], [4, 5], [6, 7], [8, 7], [1, 2], [4, 5]])
print(shape)

(6, 2)


In [ ]:
reshaped = arr.reshape(4,3)
print(reshaped)

[[1 2 4]
 [5 6 7]
 [8 7 1]
 [2 4 5]]


In [ ]:
a=np.array([[1,2,3,4],[1,2,3,4,]])
flattened = a.flatten()
print(flattened)

[1 2 3 4 1 2 3 4]


In [ ]:
transposed = arr.T
print(transposed)

[[1 4 6 8 1 4]
 [2 5 7 7 2 5]]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

10
50
[20 30 40]
[10 20 30]
[10 30 50]


In [ ]:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(matrix[1,1])
print(matrix[2,1])
print(matrix[0,2])
print(matrix[0:3,0])
print(matrix[0:3,1])
print(matrix[0:2,1:3])

50
80
30
[10 40 70]
[20 50 80]
[[20 30]
 [50 60]]


In [ ]:
arr = np.array([4, 9, 16, 25, 36])
print(arr+1)
print(arr*2)
print(arr**2)
print(np.sqrt(arr))

[ 5 10 17 26 37]
[ 8 18 32 50 72]
[  16   81  256  625 1296]
[2. 3. 4. 5. 6.]


In [ ]:
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

90
18.0
16.0


In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(np.mean(a))
print(np.var(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.0
2.0
1.4142135623730951
1
5


In [ ]:
arr = np.array([1,2,3,4,5])
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 1  3  6 10 15]
[  1   2   6  24 120]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr%20==0)
print(arr[arr%20==0])

[False  True False  True False]
[20 40]


In [ ]:
arr = np.array([3, 2, 4, 1, 5, 9, 2, 6])
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 2 3 4 5 6 9]


In [2]:
import numpy as np
arr = np.array([10, 20, 30])
view_arr = arr.view()
view_arr[0] = 100
print(arr,view_arr)

copy_arr = arr.copy()
copy_arr[0] = 200
print(arr,copy_arr)


[100  20  30] [100  20  30]
[100  20  30] [200  20  30]


In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))

[[19 22]
 [43 50]]


In [7]:
print(np.linalg.det(A))

-2.0000000000000004


In [6]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [8]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)


[-0.37228132  5.37228132]


In [11]:
C = np.array([5, 11])
solution = np.linalg.solve(A, C)
print(solution)

[1. 2.]


In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))
print(vertical_stack)
print(horizontal_stack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [16]:
split_arr = np.split(np.array([1, 2, 3, 4, 5, 6]), 3)
print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]
